### ISSUE TITLE
 redis with password does not work

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxCore#104]
When we set password to redis, gluu server is not working:
![screenshot_2018-12-28_23-09-49](https://user-images.githubusercontent.com/6398752/50526846-b9ae8b80-0af5-11e9-9c00-00c8e6da6789.png)

When I remove password on ldap entry, it work correctly.

**Comment by yuriyz** [comment]
Fixed in 3.1.5. I've tested it with redis server `requirepass foobared` configuration, all works. If during test, it will not work for you then please provide:

- redis server configuration file
- oxauth.log in TRACE log level
- ldif of oxauth configuraiton (`ou=oxauth,ou=configuration,inum=`<inum>,ou=appliances,o=gluu`)
- salt (salt used by encryptor/decryptor)

**Comment by mbaser** [comment]
Confirmed on CentOS7, it is fixed.
